# Welcome

Bem vindos ao primeiro trabalho prático da semana! Nesta prática aprenderemos sobre a linguagem de programação Python, bem como NumPy e Matplotlib, duas ferramentas fundamentais para ciência de dados e aprendizado de máquina em Python.

![](https://media.tenor.com/IVCnKbtTeRQAAAAM/programming-computer.gif)

# Notebooks

Esta semana, usaremos notebooks Jupyter e Google Colab como principal forma de praticar o aprendizado de máquina. Notebooks são uma ótima maneira de misturar código executável com conteúdos ricos (HTML, imagens, equações escritas em LaTeX). O Colab permite rodar notebooks na nuvem gratuitamente, sem qualquer instalação prévia, aproveitando ao mesmo tempo o poder do [GPUs](https://en.wikipedia.org/wiki/Graphics_processing_unit).

O documento que você está lendo não é uma página da web estática, mas um ambiente interativo chamado notebook, que permite escrever e executar código. Os notebooks consistem nas chamadas células de código, blocos de uma ou mais instruções Python. Por exemplo, aqui está uma célula de código que armazena o resultado de um cálculo (o número de segundos em um dia) em uma variável e imprime seu valor:

In [ ]:
seconds_in_a_day = 24 * 60 * 60
seconds_in_a_day

86400

Clique no botão "play" para executar a célula. Você deve ser capaz de ver o resultado. Alternativamente, você também pode executar a célula pressionando Ctrl + Enter se estiver no Windows/Linux ou Command + Enter se estiver em um Mac.

As variáveis ​​definidas em uma célula podem ser usadas posteriormente em outras células:

In [ ]:
seconds_in_a_week = 7 * seconds_in_a_day
seconds_in_a_week

604800

Observe que a ordem de execução é importante. Por exemplo, se não executarmos a célula que armazena *seconds_in_a_day* antecipadamente, a célula acima irá gerar um erro, pois depende desta variável. Para garantir que todas as células sejam executadas na ordem correta, você também pode clicar em "Tempo de execução" no menu de nível superior e depois em "Executar tudo".

**Exercício.** Adicione uma célula abaixo desta célula: clique nesta célula e depois clique em "+ Código". Na nova célula, calcule o número de segundos em um ano reutilizando a variável *seconds_in_a_day*. Execute a nova célula.

# Python

Python é uma das linguagens de programação mais populares para aprendizado de máquina, tanto na academia quanto na indústria. Como tal, é essencial aprender esta linguagem para qualquer pessoa interessada em aprendizagem de máquina. Nesta seção, revisaremos os fundamentos do Python.

## Arithmetic operations

Python suporta os operadores aritmeticos usuais: + (addition), * (multiplication), / (division), ** (power), // (integer division).

## Lists

As listas são um tipo de contêiner para sequências ordenadas de elementos. As listas podem ser inicializadas vazias

In [ ]:
my_list = []

ou com alguns elementos iniciais

In [ ]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

As listas têm um tamanho dinâmico e elementos podem ser adicionados (apendadas) a elas

In [ ]:
my_list.append(4)
my_list

[1, 2, 3, 4]

Podemos acessar elementos individuais de uma lista (a indexação começa em 0)

In [ ]:
my_list[2]

3

Podemos acessar "slices" de uma lista usando `my_list[i:j]` onde `i` inicio do slice (de novo, indexando a partir de 0) e `j` o final do "slice". Por exemplo:

In [ ]:
my_list[0:2]

[1, 2]

A omissão do segundo índice significa que o slice deve ser executada até o final da lista

In [ ]:
my_list[:2]

[1, 2]

In [ ]:
my_list

[1, 2, 3, 4]

Podemos verificar se um elemento está na lista usando `in`

In [ ]:
3 in my_list

True

O comprimento de uma lista pode ser obtido usando a função `len`

In [ ]:
len(my_list)

4

## Strings

Strings são usadas para armazenar texto. Eles podem ser delimitados usando aspas simples ou aspas duplas

In [ ]:
string1 = "some text"
string2 = 'some other text'
string3 = '''ola tudo bem'''

Strings se comportam de forma semelhante a listas. Como tal, podemos acessar elementos individuais exatamente da mesma maneira

In [ ]:
string1[3]

'e'

e da mesma forma para slices

In [ ]:
string1[5:]

'text'

In [ ]:
string3.split(' ')

['ola', 'tudo', 'bem']

In [ ]:
my_list2 = string3.split(' ')
my_list + my_list2

[1, 2, 3, 4, 'ola', 'tudo', 'bem']

A concatenação de strings é realizada usando o operador `+`

In [ ]:
string1 + " " + string2

'some text some other text'

In [ ]:
my_list + my_list

[1, 2, 3, 4, 1, 2, 3, 4]

## Conditionals

Como o nome indica, condicionais são uma forma de executar código dependendo se uma condição é verdadeira ou falsa. Como em outras linguagens, Python suporta `if` e `else` mas `else if` é contraído em `elif`, como demonstra o exemplo abaixo.

In [ ]:
my_variable = 5
if my_variable < 0:
  print("negative")
elif my_variable == 0:
  print("null")
else: # my_variable > 0
  print("positive")

positive


Aqui `<` e `>` são os operadores estritos `menos` e `maior que`, enquanto `==` é o operador de igualdade (não deve ser confundido com `=`, o operador de atribuição de variável). Os operadores `<=` e `>=` podem ser usados ​​para comparações menores (resp. maiores) ou iguais.

Ao contrário de outras linguagens, os blocos de código são delimitados por meio de identação. Aqui, usamos identação de 2 espaços, mas muitos programadores também usam identação de 4 espaços. Qualquer um funciona bem, desde que você seja consistente em todo o código.

## Loops

Loops são uma forma de executar um bloco de código várias vezes. Existem dois tipos principais de loops: loops while e loops for.

While loop

In [ ]:
i = 0
while i < len(my_list):
  print(my_list[i])
  i += 1 # equivalent to i = i + 1

1
2
3
4


For loop

In [ ]:
for i in range(len(my_list)):
  print(my_list[i])

1
2
3
4


Se o objetivo é simplesmente iterar sobre uma lista, podemos fazê-lo diretamente da seguinte maneira

In [ ]:
for i,element in enumerate(my_list):
  print(i)
  print(element)

0
1
1
2
2
3
3
4


## Functions

Para melhorar a legibilidade do código, é comum separar o código em diferentes blocos, responsáveis ​​por realizar ações precisas: funções. Uma função pega algumas entradas e as processa para retornar algumas saídas.

In [ ]:
def square(x):
  return x ** 2

def multiply(a, b):
  return a * b

# Functions can be composed.
square(multiply(3, 2))

36

In [ ]:
# prompt: create a python code that sum 2 lists

def sum_of_lists(list1, list2):
  """
  This function takes two lists of equal length and returns a new list containing the sum of the elements at each index.
  """
  if len(list1) != len(list2):
    raise ValueError("Lists must have the same length")

  sum_list = []
  for i in range(len(list1)):
    sum_list.append(list1[i] + list2[i])
  return sum_list

list1 = [1, 2, 3]
list2 = [4, 5, 6]

sum_list = sum_of_lists(list1, list2)
print(sum_list)


[5, 7, 9]


Para melhorar a legibilidade do código, às vezes é útil nomear explicitamente os argumentos

In [ ]:
square(multiply(a=3, b=2))

36

## Exercises

**Exercício 1.**Usando condicionais, escreva a função [relu](https://en.wikipedia.org/wiki/Rectifier_(neural_networks)) definida a seguir

$\text{relu}(x) = \left\{
   \begin{array}{rl}
     x, & \text{if }  x \ge 0 \\
     0, & \text{otherwise }.
   \end{array}\right.$

In [ ]:
def relu(x):
  # Write your function here
  if x >= 0:
    return x
  else:
    return 0

relu(-3)

0

**Exercício 2.** Usando um foor loop, escreva uma função que calcula a norma Euclideana [Euclidean norm](https://en.wikipedia.org/wiki/Norm_(mathematics)#Euclidean_norm) de um vetor 'vector', representado como uma lista.

In [ ]:
import numpy as np

In [ ]:
list3 = [1, 2, 3]

In [ ]:
def euclidean_norm(vector):
  # Write your function here
  soma = 0
  for element in vector:
    soma += element**2
  return np.sqrt(soma)

import numpy as np
my_vector = [0.5, -1.2, 3.3, 4.5]
# The result should be roughly 5.729746940310715
euclidean_norm(my_vector)

5.729746940310715

**Exercício 3.** Usando um for loop e uma estrutura condicional, escreva a função que retorna o máximo valor de um vetor.

In [ ]:
def vector_maximum(vector):
  # Write your function here
  valor_maximo = vector[0]
  for element in vector:
    if element > valor_maximo:
      valor_maximo - element
  return valor_maximo

vector_maximum(my_vector)

0.5

**Exercício Bonus ** se sobrar tempo, escreva uma função que ordene uma lista em ordem crescente (fdo menor para o maior) usando [bubble sort](https://en.wikipedia.org/wiki/Bubble_sort) algorithm.

In [ ]:
def bubble_sort(my_list):
  # Write your function here
  return

my_list = [1, -3, 3, 2]
# Should return [-3, 1, 2, 3]
bubble_sort(my_list)

## Indo além...

Claramente, é impossível cobrir todos os recursos linguísticos nesta breve introdução. Para ir mais longe, recomendamos os seguintes recursos:



*   List of Python [tutorials](https://wiki.python.org/moin/BeginnersGuide/Programmers)
* Four-hour [course](https://www.youtube.com/watch?v=rfscVS0vtbw) on Youtube



# NumPy

NumPy é uma biblioteca popular para armazenar matrizes de números e realizar cálculos sobre eles. Isso não apenas permite escrever código mais sucinto, mas também torna o código mais rápido, uma vez que a maioria das rotinas NumPy são implementadas em C para maior velocidade.

Para usar NumPy em seu programa, você precisa importá-lo da seguinte maneira

In [ ]:
import numpy as np

## Array creation



Arrays NumPy podem ser criadas a partir de listas Python

In [ ]:
my_array = np.array([1, 2, 3])
my_array

array([1, 2, 3])

NumPy suporta array de dimensão arbitrária. Por exemplo, podemos criar matrizes bidimensionais (por exemplo, para armazenar uma matriz) da seguinte forma:

In [ ]:
my_2d_array = np.array([[1, 2, 3], [4, 5, 6]])
my_2d_array

array([[1, 2, 3],
       [4, 5, 6]])

Podemos acessar elementos individuais de um array 2d usando dois índices

In [ ]:
my_2d_array[1, 2]

6

Acessando apenas linhas

In [ ]:
my_2d_array[1]

array([4, 5, 6])

Acessando apenas colunas

In [ ]:
# Todas as linhas da coluna 2
my_2d_array[:, 2]

array([3, 6])

Arrays tem um atributo `shape`

In [ ]:
print(my_array.shape)
print(my_2d_array.shape)

(3,)
(2, 3)


Ao contrário das listas Python, os arrays NumPy devem ter um tipo e todos os elementos do array devem ter o mesmo tipo.

In [ ]:
my_array.dtype

dtype('int64')

Os principais tipos são `int32` (32-bit integers), `int64` (64-bit integers), `float32` (32-bit real values) e `float64` (64-bit real values).

O `dtype` pode ser especificado na criação do array

In [ ]:
my_array = np.array([1, 2, 3], dtype=np.float64)
my_array.dtype

dtype('float64')

Podemos criar matrizes de todos os zeros usando

In [ ]:
zero_array = np.zeros((2, 3))
zero_array

array([[0., 0., 0.],
       [0., 0., 0.]])

e da mesma forma para todos os que usam `uns` em vez de `zeros`.

Podemos criar um intervalo de valores usando

In [ ]:
np.arange(5)

ou especificar um ponto inicial e final

In [ ]:
np.arange(3, 5)

Outra rotina útil é `linspace` para criar valores espaçados linearmente em um intervalo. Por exemplo, para criar 10 valores em `[0, 1]`, podemos usar

In [ ]:
np.linspace(0, 1, 10)

Outra operação importante é `reshape`, para alterar a forma de um array

In [ ]:
my_array = np.array([1, 2, 3, 4, 5, 6])
my_array.reshape(3, 2)

Brinque com essas operações e certifique-se de entendê-las bem.

## Basic operations

No NumPy, expressamos cálculos diretamente em arrays. Isso torna o código muito mais sucinto.

As operações aritméticas podem ser realizadas diretamente em arrays. Por exemplo, supondo que duas matrizes tenham uma forma compatível, podemos adicioná-las da seguinte forma

In [ ]:
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
array_a + array_b

Compare isso com o cálculo equivalente usando um loop for

In [ ]:
array_out = np.zeros_like(array_a)
for i in range(len(array_a)):
  array_out[i] = array_a[i] + array_b[i]
array_out

Além de esse código ser mais detalhado, ele também será executado muito mais lentamente.

No NumPy, funções que operam em arrays de maneira elemento a elemento são chamadas de [funções universais](https://numpy.org/doc/stable/reference/ufuncs.html). Por exemplo, este é o caso de `np.sin`

In [ ]:
np.sin(array_a)

O produto interno do vetor pode ser realizado usando `np.dot`

In [ ]:
np.dot(array_a, array_b)

Quando os dois argumentos para `np.dot` são ambos arrays 2d, `np.dot` torna-se multiplicação de matrizes

In [ ]:
array_A = np.random.rand(5, 3)
array_B = np.random.randn(3, 4)
np.dot(array_A, array_B)

A transposição da matriz pode ser feita usando `.transpose()` ou `.T` para abreviar

In [ ]:
array_A.T

## Slicing and masking

Like Python lists, NumPy arrays support slicing

In [ ]:
np.arange(10)[5:]

We can also select only certain elements from the array

In [ ]:
x = np.arange(10)
mask = x >= 5
x[mask]

## Exercises

**Exercicio 1.** Crie um 3d array com shape (2, 2, 2), contendo 8 valores.

**Exercise 2.** Reescreva a função ReLu usando [np.maximum](https://numpy.org/doc/stable/reference/generated/numpy.maximum.html).

In [ ]:
def relu_numpy(x):
  return

relu_numpy(np.array([1, -3, 2.5]))

**Exercise 3.** Reescreva a Norma Euclideana usando NumPy (sem usar for loop)

In [ ]:
def euclidean_norm_numpy(x):
  return

my_vector = np.array([0.5, -1.2, 3.3, 4.5])
euclidean_norm_numpy(my_vector)

**Exercise 5.** Compute the mean value of the features in the [iris dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html). Hint: use the `axis` argument on [np.mean](https://numpy.org/doc/stable/reference/generated/numpy.mean.html).

In [ ]:
from sklearn.datasets import load_iris
X, y = load_iris(return_X_y=True)

# Result should be an array of size 4.